services:
  - type: web
    name: chatbot-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    workingDir: backend/chatbot
    envVars:
      - key: GROQ_API_KEY
        sync: false
